[package]
name = "brtt"
description = "Better RTT (Real-Time Transfer) client"
version = "0.1.3"
edition = "2021"
license = "MIT"
authors = ["Michal Bogdziewicz <michal@bogdziewicz.xyz>"]

[dependencies]
env_logger = "0.11"
probe-rs = { version = "0.30.0", default-features = false, features = ["builtin-targets"] }
probe-rs-target = "0.30.0"
anyhow = "1.0"
async-io = "2.0"
clap = { version = "4", features = ["cargo", "derive"] }
crossterm = "0.27.0"
zerocopy = { version = "0.8.0", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
tracing = "0.1"
docsplay = "0.1.1"
thiserror = "2.0.11"
parking_lot = "0.12.2"
